### ISSUE TITLE
Create an apprentices per year calculator for local cities feature on the Our Data page

### ISSUE THREAD

**Issue by kamrinklauschie** [apprenticeshipio/apprenticeshipio#42]
Example: 
- Input: I live in {select: San Francisco Bay Area}, I think tech companies should hire {select: 3} apprentices per year for every 100 employees on payroll
- Result: If result: 4.434} tech companies with more than 100 employees hire {select: 3} apprentices per year, the {select: San Francisco Bay Area} would train {result: 13,302} apprentices per year 

Data: 
4,434 tech companies headquartered in in the San Francisco Bay Area with more than 100 employees  
3,010 tech companies headquartered in in New York City Metropolitan Area with more than 100 employees 
2,031 tech companies headquartered in in Washington DC Metropolitan Area with more than 100 employees
1,022 tech companies headquartered in Chicago with more than 100 employees 
957 tech companies headquartered in Seattle with more than 100 employees
912 tech companies headquartered in Houston with more than 100 employees
739 tech companies headquartered in Atlanta with more than 100 employees
708 tech companies headquartered in Los Angeles with more than 100 employees
595 tech companies headquartered in Dallas with more than 100 employees
568 tech companies headquartered in Austin with more than 100 employees
568 tech companies headquartered in Boston with more than 100 employees
357 tech companies headquartered in Minneapolis with more than 100 employees
347 tech companies headquartered in Denver with more than 100 employees
329 tech companies headquartered in Miami with more than 100 employees

**Comment by marcoscannabrava** [comment]
Just pending style

:fire: :fire: :fire:
